hosts: [
  { host_ip: "10.100.194.201", host_name: "mysql-01"},
  { host_ip: "10.100.194.202", host_name: "mysql-02"},
  { host_ip: "10.100.194.203", host_name: "mysql-03"},
  { host_ip: "10.100.194.204", host_name: "app"}
]

obsolete_services:
  - puppet
  - chef-client

centos_files: [
     { src: "centos.sshd_config", dest: "/etc/ssh/sshd_config" },
  ]